services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: pos-backend
    restart: unless-stopped
    command: sh -c "pnpm run migrate && pnpm start"
    environment:
      PORT: 3001
      NODE_ENV: production
      ADMIN_PASSWORD: "super1"
    ports:
      - "3001:3001"
    volumes:
      - ./data/sqlite/dev.db:/app/apps/backend/prisma/dev.db

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: pos-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
